/**
 * example_content.js
 * Reference example showing how a content file is structured.
 * Run with: node run.js --format docx --content content/example_content.js
 */

const { heading, paragraph, bulletItem, note } = require("../lib/helpers");
const { simpleTable } = require("../lib/tables");
const { HeadingLevel } = require("docx");

module.exports = {
  title: "Example Document",
  subtitle: "Generated by the WD DOCX Framework",
  body: [
    heading("Overview", HeadingLevel.HEADING_1),
    paragraph(
      "This is a reference example. Every real content file follows this same shape: a title, an optional subtitle, and a body array built from the helpers in lib/helpers.js and lib/tables.js."
    ),

    heading("A Bulleted List", HeadingLevel.HEADING_2),
    bulletItem("First item"),
    bulletItem("Second item"),
    bulletItem("A nested item", { level: 1 }),

    heading("A Table", HeadingLevel.HEADING_2),
    simpleTable(
      ["Column A", "Column B", "Column C"],
      [
        ["Row 1", "Value", "Value"],
        ["Row 2", "Value", "Value"],
      ]
    ),

    note("This line demonstrates the note() helper — small, italic, muted text for asides."),
  ],
};
